---
title: "Overall"
author: "Tim D. Smith"
date: "September 4, 2016"
output:
  html_document:
    dev: pdf
    self_contained: false
---

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(gplots)
library(ggplot2)
library(readr)
library(reshape2)

devtools::load_all(".")

df = load_all_cqs() %>%
  fold_vs_gapdh() %>%
  filter(Timepoint == "4h")

by_mouse = df %>%
  group_by(Target, Timepoint, Condition, Mouse) %>%
  summarize(FoldVsGapdh=mean(FoldVsGapdh, na.rm=TRUE)) %>%
  filter(!is.na(FoldVsGapdh))

by_condition = df %>%
  group_by(Target, Timepoint, Condition) %>%
  summarize(FoldVsGapdh=mean(FoldVsGapdh, na.rm=TRUE))
```

```{r semplots, fig.width=4, fig.height=6}
g = ggplot(by_mouse, aes(Condition, FoldVsGapdh)) +
  facet_wrap(~Target, ncol=2, scales="free") +
  stat_summary(fun.data=mean_se) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=40, hjust=1))
print(g)
```

```{r barplots, fig.width=7, fig.height=10}
g = ggplot(by_mouse, aes(Condition, FoldVsGapdh)) +
  facet_wrap(~Target, ncol=2, scales="free") +
  stat_summary(fun.data=mean_se, geom="bar", width=0.8) +
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.5) +
  labs(y="Fold expression vs Gapdh") +
  theme_bw() +
  theme(axis.text.x=element_text(size=8))
print(g)
```

```{r heatmap}
map_array = acast(by_mouse, Condition~Target, value.var="FoldVsGapdh", subset=.(Timepoint == "4h"), fun.aggregate=mean)
#heatmap(map_array)

#maxnorm = function(x) x/max(x)
#col_normed = apply(map_array, 2, maxnorm)
#heatmap(col_normed)

heatmap(map_array, scale="col")
```

```{r pca, fig.height=4, fig.width=4}
my_pca = prcomp(map_array, scale.=TRUE)
biplot(my_pca)
```