---
title: "Tnfa"
author: "Tim D. Smith"
date: "September 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(ggplot2)
library(readr)
library(reshape2)

devtools::load_all(".")

cqs = read_csv("raw-data/tnfa/2016-09-04 tnfa -  Quantification Summary_0.csv") %>%
  select(Well, Cq) %>%
  inner_join(annotations())

melts = read_csv("raw-data/tnfa/2016-09-04 tnfa -  Melt Curve Derivative Results_SYBR.csv") %>%
  select(-X1) %>%
  melt(id.vars="Temperature", variable.name="Well") %>%
  inner_join(annotations(zero_pad=FALSE))
```

```{r melting_curve}
g = ggplot(melts, aes(Temperature, value, color=as.factor(Col))) +
  facet_wrap(~Condition) +
  geom_line(alpha=0.7) +
  theme_bw()
print(g)
```

```{r cqs}
g = ggplot(cqs, aes(Condition, Cq, color=Mouse)) +
  geom_point() +
  facet_grid(Timepoint~.) +
  theme_bw()
print(g)
```

```{r normed}
g = cqs %>%
  fold_vs_gapdh %>%
    ggplot(aes(Condition, FoldVsGapdh, color=Mouse)) +
    geom_point() +
    facet_grid(Timepoint~., scales="free_y") +
    theme_bw()
print(g)
```